application: notifixlite
version: 1
runtime: python
api_version: 1

handlers:
- url: .*
  script: main.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

inbound_services:
- xmpp_message
